name: Build and Publish

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    strategy:
      matrix:
        workers: [download-new-data-from-url, gunzip-file]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx 🔧
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io 🔧
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.workers_names }} 🚀
        uses: docker/build-push-action@v2
        with:
          file: ./src/${{ matrix.workers }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mqm-worker/${{ matrix.workers }}:latest
