name: Build and Publish

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        uses: actions/setup-node@v2.1.5
      - run: npm ci
      - run: npm run test

      - name: Set up Docker Buildx 🔧
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io 🔧
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # downloadNewDataFromURL
      - name: Build and push downloadNewDataFromURL 🚀
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/downloadNewDataFromURL/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mqm-worker/download-new-data-from-url:latest

      # gunzipFile
      - name: Build and push gunzipFile 🚀
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/gunzipFile/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mqm-worker/gunzip-file:latest
