name: Build and Publish

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        uses: actions/setup-node@v2.1.5
      - run: npm ci
      - run: npm run test

      - name: Set up QEMU 🔧
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx 🔧
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub 🔧
        uses: docker/login-action@v1
        with:
          registry: nexus.terrestris.de
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_TOKEN }}

      # downloadNewDataFromURL
      - name: Copy downloadNewDataFromURL package.json 🔧
        uses: canastro/copy-file-action@master
        with:
          source: 'package.json'
          target: 'src/downloadNewDataFromURL/package.json'

      - name: Copy downloadNewDataFromURL package-lock.json 🔧
        uses: canastro/copy-file-action@master
        with:
          source: 'package-lock.json'
          target: 'src/downloadNewDataFromURL/package-lock.json'

      - name: Build and push downloadNewDataFromURL 🚀
        uses: docker/build-push-action@v2
        with:
          context: ./src/downloadNewDataFromURL
          push: true
          tags: nexus.terrestris.de/terrestris/mqm-worker/download-new-data-from-url:latest

      # gunzipFile
      - name: Copy gunzipFile package.json 🔧
        uses: canastro/copy-file-action@master
        with:
          source: 'package.json'
          target: 'src/gunzipFile/package.json'

      - name: Copy gunzipFile package-lock.json 🔧
        uses: canastro/copy-file-action@master
        with:
          source: 'package-lock.json'
          target: 'src/gunzipFile/package-lock.json'

      - name: Build and push gunzipFile 🚀
        uses: docker/build-push-action@v2
        with:
          context: ./src/gunzipFile
          push: true
          tags: nexus.terrestris.de/terrestris/mqm-worker/gunzip-file:latest
